api_version = "2026-07"

[[extensions]]
name = "t34-validation"
handle = "t34-validation"
type = "function"
description = "T34 acceptance cart and checkout validation (throwaway)"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
